[package]
name = "chromafree-capture"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
chromafree-core.workspace = true
chromafree-ipc.workspace = true
thiserror.workspace = true
windows = { workspace = true, features = ["Win32_Media_MediaFoundation", "Win32_System_Com"] }
