[package]
name = "chromafree-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "chromafree"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
chromafree-capture.workspace = true
chromafree-core.workspace = true
chromafree-gpu.workspace = true
chromafree-ipc.workspace = true
serde.workspace = true
slint = { version = "1.18", default-features = false, features = ["std", "backend-winit", "renderer-software", "accessibility", "compat-1-2"] }
tray-icon = "0.25"
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
windows = { workspace = true, features = ["Win32_Media_MediaFoundation", "Win32_System_Com", "Win32_Storage_FileSystem", "Win32_UI_Shell", "Win32_UI_Shell_Common", "Win32_UI_WindowsAndMessaging"] }

[build-dependencies]
embed-resource = "3"
slint-build = "1.18"
