pub mod background;
pub mod blur;
pub mod color;
pub mod composite;
pub mod error;
pub mod frame;
pub mod mask;
pub mod model_input;
pub mod orientation;
pub mod scale;
pub mod segmentation;
pub mod variant;

pub use background::RgbImage;
pub use blur::BackgroundBlur;
pub use color::{ColorMatrix, Rgb, Yuv};
pub use composite::{Background, blend_nv12, nv12_to_bgra};
pub use error::CoreError;
pub use frame::{BgraFrame, FrameSize, Mask, Nv12Frame};
pub use mask::{MaskParams, MaskRefiner};
pub use model_input::{ModelInputBuilder, TensorElement, TensorLayout};
pub use orientation::{Orientation, Rotation};
pub use scale::{Nv12Scaler, PlaneScaler, ScaleMode};
pub use segmentation::{AlphaMask, InferenceDevice, MediaPipeModel, MediaPipeVariant, RvmModel, SegmentationModel};
pub use variant::{ModelVariant, VariantPreference, available_rvm_variants, select_variant};
