[package]
name = "bgcam-probe"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
bgcam-ipc.workspace = true
windows = { workspace = true, features = ["Win32_Media_MediaFoundation", "Win32_System_Com"] }
